// All permission codes used in RBAC guards
// Format: {resource}:{action}
export const PERMISSIONS = {
  // Lessors
  LESSOR_READ: 'lessor:read',
  LESSOR_CREATE: 'lessor:create',
  LESSOR_UPDATE: 'lessor:update',
  LESSOR_ARCHIVE: 'lessor:archive',
  LESSOR_BLOCK_PAYMENT: 'lessor:block-payment',
  LESSOR_UNBLOCK_PAYMENT: 'lessor:unblock-payment',
  LESSOR_EXPORT: 'lessor:export',

  // Contracts
  CONTRACT_READ: 'contract:read',
  CONTRACT_CREATE: 'contract:create',
  CONTRACT_UPDATE: 'contract:update',
  CONTRACT_ARCHIVE: 'contract:archive',
  CONTRACT_ADDENDUM: 'contract:addendum',
  CONTRACT_TERMINATE: 'contract:terminate',
  CONTRACT_GENERATE_PDF: 'contract:generate-pdf',
  CONTRACT_EXPORT: 'contract:export',

  // Parcels
  PARCEL_READ: 'parcel:read',
  PARCEL_CREATE: 'parcel:create',
  PARCEL_UPDATE: 'parcel:update',
  PARCEL_ARCHIVE: 'parcel:archive',
  PARCEL_EXPORT: 'parcel:export',

  // Payments
  PAYMENT_READ: 'payment:read',
  PAYMENT_CREATE: 'payment:create',
  PAYMENT_APPROVE: 'payment:approve',
  PAYMENT_CANCEL: 'payment:cancel',
  PAYMENT_GENERATE_DOC: 'payment:generate-doc',
  PAYMENT_EXPORT: 'payment:export',
  PAYMENT_BATCH: 'payment:batch',

  // Invoices
  INVOICE_READ: 'invoice:read',
  INVOICE_CREATE: 'invoice:create',
  INVOICE_UPDATE: 'invoice:update',
  INVOICE_CANCEL: 'invoice:cancel',
  INVOICE_GENERATE_PDF: 'invoice:generate-pdf',
  INVOICE_CREDIT_NOTE: 'invoice:credit-note',

  // Fiscal
  FISCAL_SPV_READ: 'fiscal:spv:read',
  FISCAL_SPV_APPROVE: 'fiscal:spv:approve',
  FISCAL_SPV_SEND: 'fiscal:spv:send',
  FISCAL_DECLARATION_READ: 'fiscal:declaration:read',
  FISCAL_DECLARATION_RUN: 'fiscal:declaration:run',
  FISCAL_DECLARATION_APPROVE: 'fiscal:declaration:approve',
  FISCAL_DECLARATION_EXPORT: 'fiscal:declaration:export',

  // Documents
  DOCUMENT_READ: 'document:read',
  DOCUMENT_UPLOAD: 'document:upload',
  DOCUMENT_DELETE: 'document:delete',
  DOCUMENT_DOWNLOAD: 'document:download',

  // Reports
  REPORT_READ: 'report:read',
  REPORT_EXPORT: 'report:export',

  // Admin
  ADMIN_USERS_MANAGE: 'admin:users:manage',
  ADMIN_ROLES_MANAGE: 'admin:roles:manage',
  ADMIN_NOMENCLATURE_MANAGE: 'admin:nomenclature:manage',
  ADMIN_TEMPLATES_MANAGE: 'admin:templates:manage',
  ADMIN_SETTINGS_MANAGE: 'admin:settings:manage',
  ADMIN_AUDIT_READ: 'admin:audit:read',

  // Invoice Import (OCR)
  INVOICE_IMPORT_READ: 'invoice:import:read',
  INVOICE_IMPORT_CREATE: 'invoice:import:create',
  INVOICE_IMPORT_REVIEW: 'invoice:import:review',
  INVOICE_IMPORT_APPROVE: 'invoice:import:approve',

  // Contract Files
  CONTRACT_FILE_UPLOAD: 'contract:file:upload',
  CONTRACT_FILE_READ: 'contract:file:read',

  // Tenants (SUPER_ADMIN only)
  TENANT_READ: 'tenant:read',
  TENANT_CREATE: 'tenant:create',
  TENANT_UPDATE: 'tenant:update',
  TENANT_SUSPEND: 'tenant:suspend',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

// Default permissions per role
export const ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  TENANT_ADMIN: [
    PERMISSIONS.LESSOR_READ, PERMISSIONS.LESSOR_CREATE, PERMISSIONS.LESSOR_UPDATE,
    PERMISSIONS.LESSOR_ARCHIVE, PERMISSIONS.LESSOR_BLOCK_PAYMENT, PERMISSIONS.LESSOR_UNBLOCK_PAYMENT, PERMISSIONS.LESSOR_EXPORT,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_CREATE, PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_ARCHIVE, PERMISSIONS.CONTRACT_ADDENDUM, PERMISSIONS.CONTRACT_TERMINATE,
    PERMISSIONS.CONTRACT_GENERATE_PDF, PERMISSIONS.CONTRACT_EXPORT,
    PERMISSIONS.PARCEL_READ, PERMISSIONS.PARCEL_CREATE, PERMISSIONS.PARCEL_UPDATE, PERMISSIONS.PARCEL_ARCHIVE, PERMISSIONS.PARCEL_EXPORT,
    PERMISSIONS.PAYMENT_READ, PERMISSIONS.PAYMENT_CREATE, PERMISSIONS.PAYMENT_APPROVE,
    PERMISSIONS.PAYMENT_CANCEL, PERMISSIONS.PAYMENT_GENERATE_DOC, PERMISSIONS.PAYMENT_EXPORT, PERMISSIONS.PAYMENT_BATCH,
    PERMISSIONS.INVOICE_READ, PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_CANCEL, PERMISSIONS.INVOICE_GENERATE_PDF, PERMISSIONS.INVOICE_CREDIT_NOTE,
    PERMISSIONS.FISCAL_SPV_READ, PERMISSIONS.FISCAL_SPV_APPROVE, PERMISSIONS.FISCAL_SPV_SEND,
    PERMISSIONS.FISCAL_DECLARATION_READ, PERMISSIONS.FISCAL_DECLARATION_RUN,
    PERMISSIONS.FISCAL_DECLARATION_APPROVE, PERMISSIONS.FISCAL_DECLARATION_EXPORT,
    PERMISSIONS.DOCUMENT_READ, PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_DELETE, PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ADMIN_USERS_MANAGE, PERMISSIONS.ADMIN_ROLES_MANAGE, PERMISSIONS.ADMIN_NOMENCLATURE_MANAGE,
    PERMISSIONS.ADMIN_TEMPLATES_MANAGE, PERMISSIONS.ADMIN_SETTINGS_MANAGE, PERMISSIONS.ADMIN_AUDIT_READ,
  ],

  CONTRACTS_OP: [
    PERMISSIONS.LESSOR_READ, PERMISSIONS.LESSOR_CREATE, PERMISSIONS.LESSOR_UPDATE, PERMISSIONS.LESSOR_ARCHIVE,
    PERMISSIONS.LESSOR_BLOCK_PAYMENT, PERMISSIONS.LESSOR_EXPORT,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_CREATE, PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_ADDENDUM, PERMISSIONS.CONTRACT_TERMINATE, PERMISSIONS.CONTRACT_GENERATE_PDF, PERMISSIONS.CONTRACT_EXPORT,
    PERMISSIONS.PARCEL_READ, PERMISSIONS.PARCEL_CREATE, PERMISSIONS.PARCEL_UPDATE, PERMISSIONS.PARCEL_EXPORT,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.DOCUMENT_READ, PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
  ],

  PAYMENTS_OP: [
    PERMISSIONS.LESSOR_READ, PERMISSIONS.LESSOR_BLOCK_PAYMENT, PERMISSIONS.LESSOR_UNBLOCK_PAYMENT,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_GENERATE_PDF,
    PERMISSIONS.PARCEL_READ,
    PERMISSIONS.PAYMENT_READ, PERMISSIONS.PAYMENT_CREATE, PERMISSIONS.PAYMENT_APPROVE,
    PERMISSIONS.PAYMENT_CANCEL, PERMISSIONS.PAYMENT_GENERATE_DOC, PERMISSIONS.PAYMENT_EXPORT, PERMISSIONS.PAYMENT_BATCH,
    PERMISSIONS.INVOICE_READ, PERMISSIONS.INVOICE_GENERATE_PDF,
    PERMISSIONS.DOCUMENT_READ, PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
  ],

  ACCOUNTANT: [
    PERMISSIONS.LESSOR_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_GENERATE_PDF,
    PERMISSIONS.PARCEL_READ,
    PERMISSIONS.PAYMENT_READ, PERMISSIONS.PAYMENT_GENERATE_DOC,
    PERMISSIONS.INVOICE_READ, PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_GENERATE_PDF, PERMISSIONS.INVOICE_CREDIT_NOTE,
    PERMISSIONS.FISCAL_SPV_READ, PERMISSIONS.FISCAL_SPV_APPROVE, PERMISSIONS.FISCAL_SPV_SEND,
    PERMISSIONS.FISCAL_DECLARATION_READ, PERMISSIONS.FISCAL_DECLARATION_RUN,
    PERMISSIONS.FISCAL_DECLARATION_APPROVE, PERMISSIONS.FISCAL_DECLARATION_EXPORT,
    PERMISSIONS.DOCUMENT_READ, PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
  ],

  REPORTING_OP: [
    PERMISSIONS.LESSOR_READ, PERMISSIONS.LESSOR_EXPORT,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_EXPORT,
    PERMISSIONS.PARCEL_READ, PERMISSIONS.PARCEL_EXPORT,
    PERMISSIONS.PAYMENT_READ, PERMISSIONS.PAYMENT_EXPORT,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.FISCAL_SPV_READ, PERMISSIONS.FISCAL_DECLARATION_READ,
    PERMISSIONS.DOCUMENT_READ, PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
  ],

  VIEWER: [
    PERMISSIONS.LESSOR_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.PARCEL_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.REPORT_READ,
  ],

  SUPPORT_ADMIN: [
    PERMISSIONS.LESSOR_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.PARCEL_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.ADMIN_AUDIT_READ,
  ],
}
