/**
 * ANAF e-Transport API client.
 *
 * Docs: https://mfinante.gov.ro/ro/web/etransport/informatii-tehnice
 * API base:
 *   test → https://api.anaf.ro/test/ETRANSPORT/ws/etransport/v2
 *   prod → https://api.anaf.ro/prod/ETRANSPORT/ws/etransport/v2
 *
 * Auth: same Bearer token as e-Factura (anaf_oauth_tokens table).
 */

import type { ETransportUploadResponse, ETransportDeleteResponse } from './types'

export type AnafEnv = 'test' | 'prod'

const BASE: Record<AnafEnv, string> = {
  test: 'https://api.anaf.ro/test/ETRANSPORT/ws/etransport/v2',
  prod: 'https://api.anaf.ro/prod/ETRANSPORT/ws/etransport/v2',
}

export class AnafETransportClient {
  private readonly baseUrl: string

  constructor(
    private readonly token: string,
    env: AnafEnv = 'test',
  ) {
    this.baseUrl = BASE[env]
  }

  /**
   * Upload an e-Transport declaration XML to ANAF.
   * Returns the cod_UIT generated by ANAF.
   */
  async declare(xml: string, cif: string): Promise<{ cod_uit: string; raw: ETransportUploadResponse }> {
    const cifNum = cif.replace(/\s/g, '').replace(/^RO/i, '')
    const url = `${this.baseUrl}/upload?cif=${encodeURIComponent(cifNum)}`

    const ctrl = new AbortController()
    const t = setTimeout(() => ctrl.abort(), 15000)
    let res: Response
    try {
      res = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/xml',
          Authorization: `Bearer ${this.token}`,
        },
        body: xml,
        signal: ctrl.signal,
      })
    } finally {
      clearTimeout(t)
    }

    const rawText = await res.text()
    if (!res.ok) {
      throw new Error(`ANAF e-Transport upload HTTP ${res.status}: ${rawText.slice(0, 400)}`)
    }

    let body: ETransportUploadResponse
    try {
      body = JSON.parse(rawText) as ETransportUploadResponse
    } catch {
      throw new Error(`ANAF e-Transport: răspuns JSON invalid: ${rawText.slice(0, 200)}`)
    }

    if (body.ExecutionStatus !== '0' && body.ExecutionStatus !== undefined) {
      const errs = body.Errors?.map(e => e.errorMessage).join('; ') ?? 'Eroare necunoscută ANAF'
      throw new Error(`ANAF e-Transport respins: ${errs}`)
    }

    const cod_uit = body.cod_UIT ?? ''
    if (!cod_uit) throw new Error('ANAF e-Transport: lipsă cod_UIT în răspuns')

    return { cod_uit, raw: body }
  }

  /**
   * Cancel (delete) a previously declared UIT.
   */
  async cancel(cod_uit: string, cif: string): Promise<ETransportDeleteResponse> {
    const cifNum = cif.replace(/\s/g, '').replace(/^RO/i, '')
    const url = `${this.baseUrl}/stergere?cif=${encodeURIComponent(cifNum)}&cod_UIT=${encodeURIComponent(cod_uit)}`

    const ctrl = new AbortController()
    const t = setTimeout(() => ctrl.abort(), 10000)
    let res: Response
    try {
      res = await fetch(url, {
        method: 'DELETE',
        headers: { Authorization: `Bearer ${this.token}` },
        signal: ctrl.signal,
      })
    } finally {
      clearTimeout(t)
    }

    const rawText = await res.text()
    if (!res.ok) {
      throw new Error(`ANAF e-Transport stergere HTTP ${res.status}: ${rawText.slice(0, 400)}`)
    }

    try {
      return JSON.parse(rawText) as ETransportDeleteResponse
    } catch {
      return {}
    }
  }
}
